[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]
solc="0.8.20"

[rpc_endpoints]
"${NETWORK}"="${RPC_URl}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
