[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]
solc="0.8.23"

[rpc_endpoints]
base_sepolia="${RPC_URL}"

[etherscan]
base_sepolia={key="${BLOCK_EXPLORER_API_KEY}",url="${BLOCK_EXPLORER}"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
